Repository Akash-Kumar-Sen/EdexCare, pull requests merged in 2021-10, with the labels that each got.

#4 created login page
  login.html
Labels: Hacktoberfest, hacktoberest-accepted

#9 newUi file added
  templates/newUI/newUI.html
Labels: Hacktoberfest, hacktoberest-accepted, UI

#10 Created a Sign-up Page #5
  templates/accounts/signup.html
Labels: enhancement, Hacktoberfest, hacktoberest-accepted

#13 updated the test ui
  templates/newUI/test.py
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#15 views.py file updated
  templates/newUI/views.py
Labels: enhancement, Hacktoberfest, hacktoberest-accepted

#16 Navbar fix
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  HomeActions/__pycache__/__init__.cpython-39.pyc
  HomeActions/__pycache__/admin.cpython-39.pyc
  HomeActions/__pycache__/apps.cpython-39.pyc
  HomeActions/__pycache__/forms.cpython-39.pyc
  HomeActions/__pycache__/models.cpython-39.pyc
  HomeActions/__pycache__/urls.cpython-39.pyc
  HomeActions/__pycache__/views.cpython-39.pyc
  HomeActions/migrations/__pycache__/0001_initial.cpython-39.pyc
  HomeActions/migrations/__pycache__/0002_homeactions_icon_class.cpython-39.pyc
  HomeActions/migrations/__pycache__/0003_homeactions_hex_color.cpython-39.pyc
  HomeActions/migrations/__pycache__/0004_homeactions_name_slug.cpython-39.pyc
  HomeActions/migrations/__pycache__/0005_alter_homeactions_name_slug.cpython-39.pyc
  HomeActions/migrations/__pycache__/0006_homeactions_large_description.cpython-39.pyc
  HomeActions/migrations/__pycache__/0007_homeactions_large_description_doc.cpython-39.pyc
  HomeActions/migrations/__pycache__/0008_remove_homeactions_large_description.cpython-39.pyc
  HomeActions/migrations/__pycache__/0009_auto_20210927_2149.cpython-39.pyc
  HomeActions/migrations/__pycache__/0010_customerresponse.cpython-39.pyc
  HomeActions/migrations/__pycache__/__init__.cpython-39.pyc
  djenv/pyvenv.cfg
  edxcare/__pycache__/__init__.cpython-38.pyc
  edxcare/__pycache__/__init__.cpython-39.pyc
  edxcare/__pycache__/settings.cpython-38.pyc
  edxcare/__pycache__/settings.cpython-39.pyc
  edxcare/__pycache__/urls.cpython-39.pyc
  edxcare/__pycache__/views.cpython-39.pyc
  edxcare/__pycache__/wsgi.cpython-39.pyc
  edxcare/static/style-1.css
  edxcare/static/style-2.css
  events/__pycache__/__init__.cpython-39.pyc
  events/__pycache__/admin.cpython-39.pyc
  events/__pycache__/apps.cpython-39.pyc
  events/__pycache__/forms.cpython-39.pyc
  events/__pycache__/models.cpython-39.pyc
  events/migrations/__pycache__/0001_initial.cpython-39.pyc
  events/migrations/__pycache__/0002_testimonial_image.cpython-39.pyc
  events/migrations/__pycache__/0003_auto_20210929_2105.cpython-39.pyc
  events/migrations/__pycache__/__init__.cpython-39.pyc
  requirements.txt
  static/style-1.css
  static/style-2.css
  templates/home.html
  templates/includes/navbar.html
  templates/includes/navbar.txt
  templates/nav-links/aboutus.html
  templates/nav-links/contactus.html
  templates/nav-links/resources.html
Labels: Hacktoberfest, hacktoberest-accepted

#19 created preloader
  templates/Preloader.html
Labels: Hacktoberfest, hacktoberest-accepted
